Adding link to BTCPay for WooCommerce V2 video.
btcpayserver/btcpayserver-doc pull request #1034
Opened 2022-02-28 12:27 UTC by ndeet

@NicolasDorier I saw you removed the old video [here](https://github.com/btcpayserver/btcpayserver-doc/commit/d4eecd82a811500407770ab97e5dd8fd3fd64a5f) but I just forgot to update the link to the new video. Somebody is also working on improving my video so there will be a better one in the next few days and I will reopen the PR.

2022-03-03 09:36 UTC, pavlenex approved these changes

2022-03-03 09:40 UTC, pavlenex requested changes
Actually, do we have another video added the one by webworthy?

2022-03-03 22:27 UTC, ndeet commented
@pavlenex yes we have a much better video from webworthy, but I still wait until someone with access to BTCPay YouTube channel uploads it there (and pings me when ready); see discussion on ~documentation channel

2022-03-04 23:17 UTC, ndeet commented
Vid on the BTCPay YT channel now linked 🚀

2022-03-05 07:39 UTC, pavlenex approved these changes

2022-03-05 07:40 UTC, merged