PR for issue 998 - only missing new video content
btcpayserver/btcpayserver-doc pull request #1066
Opened 2022-03-29 21:11 UTC by Bangalisch

Just needs new video content.
Moved Testnet away from this page as a avg user will not use it. 
It was moved to Deployment.

#998

2022-03-29 21:28 UTC, Bangalisch commented
#998

2022-03-30 09:07 UTC, pavlenex requested changes
Nice idea, agreed with it, but I think `Developers` is better suitable place for this then deployment. Dev are more likely to use testnet to test things out then people trying to find docs on how to actually deploy btcpay, though the line is thin there, I suggest we add it in `Developers` docs, specifically here:

![Screenshot 2022-03-30 at 11 06 11](https://user-images.githubusercontent.com/36959754/160795114-04d338ee-3d08-447d-9b2e-bf5e98da0b89.png)

What do you say?

2022-03-30 16:15 UTC, Bangalisch commented
Agreed! 
Wasnt to sure about the Testnet stuff where to put it, but ur right! 
Lets move it there

2022-03-31 09:37 UTC, dennisreimann commented on docs/.vuepress/config.js
> +      ['/TryItOut', 'Try it out']
```suggestion
      ['/TryItOut', 'Try it out'],
```

2022-03-31 09:49 UTC, merged