Feat/create wallet doc update
btcpayserver/btcpayserver-doc pull request #1078
Opened 2022-04-02 03:24 UTC by dafunction

i added a new block for the transaction signing page 'Advanced Settings' and i'll admit i'm a bit unsure if what i wrote is correct regarding the 'Import Keys to RPC' option.  also open to removing that 'Advanced Settings' block if folks feel it's unnecessary or out of place.

2022-04-02 18:23 UTC, Bangalisch requested changes
disregard this.. i messed up on my comment. I did run it trough Grammarly tho :)

2022-04-02 18:29 UTC, Bangalisch commented on docs/CreateWallet.md
> +After creating a store, you'll be able to attach a wallet by first navigating to the sidebar or slide out menu and clicking/tapping the **Bitcoin** button under the **Wallets** header. Alternatively,
```suggestion
After creating a store, you'll be able to attach a wallet by first navigating to the sidebar or slide-out menu and clicking/tapping the **Bitcoin** button under the **Wallets** header. Alternatively, you can find the option to **Set up a wallet** on the Dashboard.
```

2022-04-02 18:43 UTC, Bangalisch reviewed
Grammarly polishing :) 
Some typos and some rephrasing. 
Good job !! :D

2022-04-02 18:43 UTC, Bangalisch commented on docs/CreateWallet.md
> +For a hot wallet you'll focus on the **I don't have a wallet** section and clicking/tapping the **Create a new wallet** button.
```suggestion
You'll focus on the **I don't have a wallet** section for a hot wallet and click the **Create a new wallet** button.
```

2022-04-02 18:43 UTC, Bangalisch commented on docs/CreateWallet.md
> +On the proceeding page there will be two options, and in this case we'll select the **Hot wallet** button.
```suggestion
There will be two options on the proceeding page, and in this case, we'll select the **Hot wallet** button.
```

2022-04-02 18:43 UTC, Bangalisch commented on docs/CreateWallet.md
> +For most folks, the default options including **Address Type** (Segwit), should work well for most applications and it's recommended to not change it unless you're sure of what you're doing. The **Pa
```suggestion
For most people, the default options, including **Address Type** (Segwit), should work well for most applications, and it's recommended not to change it unless you're sure of what you're doing. The **Payjoin** feature is optional, and you can learn more about it at the link [above](#hot-wallet).
```

2022-04-02 18:43 UTC, Bangalisch commented on docs/CreateWallet.md
> +    - This is for more advanced applicaitons of BTCPay Server.  Importing your keys to RPC will allow for users to leverage [bitcoind Wallet RPCs](https://developer.bitcoin.org/reference/rpc/index.ht
```suggestion
    - This is for more advanced applications of BTCPay Server.  Importing your keys to RPC will allow users to leverage [bitcoind Wallet RPCs](https://developer.bitcoin.org/reference/rpc/index.html#wallet-rpcs) on the imported wallet.
```

2022-04-02 18:43 UTC, Bangalisch commented on docs/CreateWallet.md
>  Once you’ve received funds to your wallet and you decide to spend them, you can sign the transaction automatically, all inside BTCPay Server.
```suggestion
Once you've received funds to your wallet and decide to spend them, you can automatically sign the transaction inside BTCPay Server.
```

2022-04-02 18:43 UTC, Bangalisch commented on docs/CreateWallet.md
> +3. Adjust the transaction settings including fee rate, confirmation time preference, and if you'd like trasaction fees to be subtracted from the amount you're sending
```suggestion
3. Adjust the transaction settings, including fee rate, confirmation time preference, and if you'd like transaction fees to be subtracted from the amount you're sending
```

2022-04-02 18:43 UTC, Bangalisch commented on docs/CreateWallet.md
>  As mentioned above, the create wallet functionality includes risk of funds being stolen in the case of the server or account being compromised. To mitigate this risk, we advise you to:
```suggestion
As mentioned above, the create wallet functionality includes the risk of funds being stolen if the server or account is compromised. To mitigate this risk, we advise you to:
```

2022-04-02 18:43 UTC, Bangalisch commented on docs/CreateWallet.md
>  Similar to the hot wallet, the watch-only wallet can get your store connected to a wallet instantly. In contrast, this option does not store the private keys on the server. As a result the wallet bec
```suggestion
Like the hot wallet, the watch-only wallet can instantly get your store connected to a wallet. In contrast, this option does not store the private keys on the server. As a result, the wallet becomes "watch-only" for any received funds.
```

2022-04-02 18:43 UTC, Bangalisch commented on docs/CreateWallet.md
> +Alternatively you can spend funds in another external wallet where you have imported your BTCPay Server produced seed words.  If you do import your seed words into an external wallet, you can also us
```suggestion
Alternatively, you can spend funds in another external wallet where you have imported your BTCPay Server-produced seed words.  If you import your seed words into an external wallet, you can also use a PSBT to spend the funds, assuming the wallet supports it.  This option will be available on the wallet's send page.  Be sure to consider the [gap limit issue](./FAQ/Wallet.md#missing-payments-in-my-software-or-hardware-wallet) if you're using an external wallet with your watch-only wallet.
```

2022-04-10 23:47 UTC, Bangalisch commented on docs/CreateWallet.md
> +### 🔥 Hot Wallet
```suggestion
###  Hot Wallet
```

2022-04-10 23:47 UTC, Bangalisch commented on docs/CreateWallet.md
> +#### 🌱 Recovery Seed
```suggestion
####  Recovery Seed
```

2022-04-10 23:48 UTC, Bangalisch commented on docs/CreateWallet.md
> +#### ⚙️ Advanced Settings
```suggestion
####  Advanced Settings
```

2022-04-10 23:48 UTC, Bangalisch commented on docs/CreateWallet.md
> +### 👀 Watch-only wallet
```suggestion
###  Watch-only wallet
```

2022-04-10 23:50 UTC, Bangalisch commented on docs/CreateWallet.md
> +Find out more about advanced settings [here](#⚙️-advanced-settings).
```suggestion
Find out more about advanced settings [here](#advanced-settings).
```

2022-04-11 01:55 UTC, dafunction commented
Thanks for that @Bangalisch!
I've gone ahead and committed your changes to this branch.

2022-04-11 15:11 UTC, Bangalisch commented
Awesome! 

@pavlenex might wanna do one more run over it ^^

2022-04-12 09:38 UTC, pavlenex approved these changes

2022-04-12 09:38 UTC, pavlenex commented on docs/CreateWallet.md
> +The last step to creating a hot wallet is making sure you document your recovery seed.  After you've done so, tick the checkbox that says *I have written down my recovery phrase and stored it in a se
Double space
```suggestion
The last step to creating a hot wallet is making sure you document your recovery seed. After you've done so, tick the checkbox that says *I have written down my recovery phrase and stored it in a secure location* and click the **Done** button.
```

2022-04-12 09:50 UTC, pavlenex approved these changes
Good additions thanks to both of you for going through it and improving. I'll merge this now, I feel like `#### Spending funds with BTCPay Hot Wallet` and watch-only wallet should be in the `wallets` page so perhaps adding those there would make more sense, since I think we already talk about spending steps on that page.

2022-04-12 09:51 UTC, merged