Addition to FAQ for Email Rules
btcpayserver/btcpayserver-doc pull request #1178
Opened 2022-10-30 14:40 UTC by Bangalisch

Yo yo

Made an entry to FAQ for email rules.

closes #1173

2022-10-31 09:30 UTC, dennisreimann commented on docs/Notifications.md
> +Set a recipient Email address where you'd want to be updated by Email on store events, or tick the option for `Send email to the buyer if an email was provided to the invoice`.
```suggestion
Set a recipient email address where you'd want to be updated by email on store events, or tick the option for `Send email to the buyer if an email was provided to the invoice`.
```

2022-10-31 09:30 UTC, dennisreimann commented on docs/Notifications.md
> +Fill out a subject for the event Email, and you can stylize the body of the Email at last.
```suggestion
Fill out a subject for the event email, and you can stylize the body of the email at last.
```

2022-11-03 13:11 UTC, pavlenex approved these changes

2022-11-03 14:09 UTC, Kukks requested changes

2022-11-03 14:09 UTC, Kukks commented on docs/Notifications.md
> +            {Invoice.StoreId}
```suggestion
            {Invoice.Id}
            {Invoice.StoreId}
```

2022-11-03 14:09 UTC, Kukks commented on docs/Notifications.md
> +            {Invoice.AdditionalStatus}
```suggestion
```

2022-11-08 20:19 UTC, merged