open cart doc improvement
btcpayserver/btcpayserver-doc pull request #1422
Opened 2024-08-29 15:54 UTC by TChukwuleta

Part implementation of #1352 for Open cart.

2024-10-02 10:37 UTC, pavlenex commented
I wont' be prioritizng a review on this one for a few weeks, quick glance it's really overwhelmingly screams chatgpt. If you could actually proofread it yourself and rephrase I could then prioritize it.

2024-11-18 11:49 UTC, pavlenex requested changes
@TChukwuleta As said above, if you're using chatgpt, please proofread to ensure accuracy before pushing a PR, it takes more time to edit out this PR from repetative unecessary marketing buzzwords than it takes to generate it.

Most of the changes are okay, but please re-write the feature and benefits section according to my comments.

2024-11-18 11:49 UTC, pavlenex commented on docs/OpenCart.md
> +# BTCPay Server Integration with OpenCart: A Complete Guide
```suggestion
# Accept Bitcoin payments in OpenCart
```

2024-11-18 11:49 UTC, pavlenex commented on docs/OpenCart.md
> +[BTCPay Server](https://btcpayserver.org/) is a free and open-source cryptocurrency payment processor. It allows you receive payments in Bitcoin and altcoins directly into your wallet with no fees, t
Please, if you're doing chatgpt proofread the output. How is there no transaction cost?
```suggestion
[BTCPay Server](https://btcpayserver.org/) is a free and open-source bitcoin payment processor. It allows you receive payments directly into your wallet with no fees or a middleman.
```

2024-11-18 11:49 UTC, pavlenex commented on docs/OpenCart.md
> + If you run an OpenCart store, integrate your store today with BTCPay Server to help expand your payment options, attract crypto-savvy customers, without paying a dime.
Unnecessary marketing buzzwords
```suggestion
 If you run an OpenCart store, integrate your store today with BTCPay Server to help expand your payment options, attract crypto-savvy customers, without paying a dime.
```

2024-11-18 11:49 UTC, pavlenex commented on docs/OpenCart.md
> +BTCPay Server is a non-custodial invoicing system that ensures complete control over your payments by eliminating third-party involvement. With the BTCPay Server OpenCart extension, payments are sent
Didn't we already mention this on line 11, why repeating it?
```suggestion
```

2024-11-18 11:49 UTC, pavlenex commented on docs/OpenCart.md
> +## Why Choose BTCPay Server: Unmatched Benefits for Your Payment Processing
```suggestion
## Benefits of using BTCPay for OpenCart
```

2024-11-18 11:49 UTC, pavlenex commented on docs/OpenCart.md
> +BTCPay Server can be deployed as a self-hosted solution on your server, or you can opt for a third-party host. The self-hosted option not only allows you to manage an unlimited number of stores and l
Be concise here, let's just use bulletpoints, this chatgpt mumbo jumbo is becoming annoying and adds zero value just words.

2024-11-19 06:26 UTC, TChukwuleta commented
Reviewed them... Apologies for the stress...

Can you take another look @pavlenex

2024-11-27 11:04 UTC, pavlenex approved these changes

2024-11-27 11:04 UTC, merged