Manual deployment warnings
btcpayserver/btcpayserver-doc pull request #771
Opened 2020-11-16 16:32 UTC by Zaxounette

Relates to #769 .
Adresses the initial issue, but not the suggestion in https://github.com/btcpayserver/btcpayserver-doc/issues/769#issuecomment-727656623 

* Convert an existing sentence into a warning in `Deployment.md`
* Add a short bold indication in the options bullet-points in `Deployment.md`
* Copy warning from `ExtendedManualDeployment.md` into `ManualDeployment.md`, just under the first H1
* Include an additional sentence to be explicit the community will not provide extensive support/support time for this deployment
* Add this additional sentence to already existing warning in `ManualDeploymentExtended.md`
* Add warning in `Troubleshooting.md` in the "Ask for help" section.

2020-11-16 16:38 UTC, Zaxounette commented
`├─BROKEN─ https://docs.drupalcommerce.org/commerce2/developer-guide/install-update/installation (BLC_UNKNOWN)` is unrelated to this PR.
Invalid certificat, the link works fine if certificat warning is discarded.

2020-11-19 03:20 UTC, britttttk requested changes
@Zaxounette awesome thanks for finding these warning spots. 

I know this warning is a bit repetitive but this document is linked in the btcpayserver repo's Github new issue page, so I think it would be good to make it very clear here. 

I inverted your statement because technically the community is never required to provide anyone extensive support. It's just FOSS :D but solving all custom issues is definitely not a priority.

2020-11-19 03:20 UTC, britttttk commented on docs/Troubleshooting.md
> +The community will only provide extensive support for production deployments. i.e. [Manual Deployments](ManualDeployment.md) are not intended for production use.
```suggestion
The community will not provide extensive support for custom deployments. i.e. Variations of [Manual Deployments](ManualDeployment.md) are expected to be used only for development purposes and by users with technical literacy with the ability to **resolve deployment and maintenance issues on their own**. 
```

2020-11-19 16:03 UTC, Zaxounette commented on docs/Troubleshooting.md
> +The community will only provide extensive support for production deployments. i.e. [Manual Deployments](ManualDeployment.md) are not intended for production use.
Nice wording :)

2020-11-19 16:55 UTC, Zaxounette commented
Failed linkcheck `├─BROKEN─ https://bitcoinshirt.co/btcpay-stores/ (BLC_UNKNOWN)` unrelated to this PR.

2020-11-20 06:22 UTC, merged