Update Support
btcpayserver/btcpayserver-doc pull request #830
Opened 2021-01-29 05:52 UTC by GraemeConradie

2021-01-29 17:48 UTC, Zaxounette approved these changes

2021-01-29 17:49 UTC, Zaxounette requested changes

2021-01-29 17:49 UTC, Zaxounette commented on docs/Support.md
>  > I can help with initial setup/deployment (currently with Azure, but I am planning to play with non-Azure as wll) and integration with PrestaShop. I was also playing with design customization of the
```suggestion
> I can help with initial setup/deployment (currently with Azure, but I am planning to play with non-Azure as well) and integration with PrestaShop. I was also playing with design customization of the payment window, scripting of exchange rates etc.
```
Let's fix this typo while we're here.

2021-01-30 19:34 UTC, dennisreimann commented
Looks good to me. Build fixed on master.

2021-01-31 01:44 UTC, merged