update manual deployment with testnet commands
btcpayserver/btcpayserver-doc pull request #843
Opened 2021-02-16 20:21 UTC by rukykf

I recently had to do a minimal setup of BTCPayServer in testnet mode and it took me a while to find the testnet commands to do it so I thought these additions to the docs might be helpful.

2021-02-16 21:08 UTC, Zaxounette requested changes
Hi @rukykf ! 

Thanks for this addition.

On the wording and formatting side, to separate explicitly mainnet and testnet deployments, it would be preferable to
* Add these commands as a seperate H2 title, right before "Additionnal links".
* Include a simple line at the beginning of the file with a wording in the lines of `For Testnet specific deployment, see [LINK TO BOTTOM OF PAGE WHERE YOU COMMANDS ARE].` 

As for the actual code, i'll leave that to @britttttk .

2021-02-16 22:12 UTC, rukykf commented
Thanks for your feedback @Zaxounette. I just made the changes you requested.

2021-02-16 23:06 UTC, Zaxounette approved these changes
ACK for wording and formatting, thanks for the rapid changes =)

FYI, we have a ContributeDevTest.md file that relates to testing BTCPay, but in regtest and locally only.
Britt might want to add these commands to that particular file instead.
Will wait on her input.

2021-02-18 07:58 UTC, britttttk approved these changes

2021-02-25 17:23 UTC, merged