added required steps if you use a custom domain
btcpayserver/btcpayserver-doc pull request #849
Opened 2021-02-18 09:53 UTC by zevaverbach

Fixed a few typos too, and mentioned you have to log in to see the blockchain sync status. 

Without these additional steps, you get a 503 error when visiting the domain.

Note: I didn't test using a generated domain, so that may also be broken for all I know.

2021-02-18 10:12 UTC, dennisreimann approved these changes

2021-02-18 10:13 UTC, dennisreimann commented
Thanks for the contribution, this looks good to me.

2021-02-18 10:25 UTC, pavlenex requested changes

2021-02-18 10:25 UTC, pavlenex commented on docs/LunaNodeWebDeployment.md
> +$ export BTCPAY_HOST=btc.helpers.fun
please use generic domain name here

2021-02-18 11:16 UTC, zevaverbach commented on docs/LunaNodeWebDeployment.md
> +$ export BTCPAY_HOST=btc.helpers.fun
ooh, good catch

2021-02-18 17:26 UTC, Zaxounette reviewed
Just a comment to ask how crucial these command steps are ?

Because I've deployed multiple instances through the Lunanode Webwizard, with custom domain, and have never had to go CLI. The web-wizard includes the custom domain initial config.

2021-02-18 17:26 UTC, Zaxounette commented on docs/LunaNodeWebDeployment.md
> +Their web-wizard is one of the easiest ways to **deploy BTCPay Servers from a very user-friendly interface**. This method is highly recommended if you don't have a lot of technical knowledge. However
```suggestion
Their web-wizard is one of the easiest ways to **deploy BTCPay Servers from a very user-friendly interface**. This method is highly recommended if you don't have a lot of technical knowledge. However, if you set up a custom domain you will need to have some comfort with the command line interface.
```

2021-02-18 17:26 UTC, Zaxounette commented on docs/LunaNodeWebDeployment.md
> +Their web-wizard is one of the easiest ways to **deploy BTCPay Servers from a very user-friendly interface**. This method is highly recommended if you don't have a lot of technical knowledge. However
Just making CLI generic instead of Shell specific. 
An unfamiliar user wouldn't know what shell is.

2021-02-18 20:16 UTC, zevaverbach commented
> Just a comment to ask how crucial these command steps are ?
> 
> Because I've deployed multiple instances through the Lunanode Webwizard, with custom domain, and have never had to go CLI. The web-wizard includes the custom domain initial config.

@Zaxounette it didn't work for me without those steps, which I gathered from [here](https://github.com/btcpayserver/btcpayserver-docker/issues/52).

2021-02-18 20:21 UTC, Zaxounette approved these changes

2021-02-21 06:58 UTC, britttttk requested changes

2021-02-21 06:58 UTC, britttttk commented on docs/LunaNodeWebDeployment.md
> +Their web-wizard is one of the easiest ways to **deploy BTCPay Servers from a very user-friendly interface**. This method is highly recommended if you don't have a lot of technical knowledge. However
```suggestion
Their web-wizard is one of the easiest ways to **deploy BTCPay Servers from a very user-friendly interface**. This method is highly recommended if you don't have a lot of technical knowledge. LunaNode will provide you with a generic domain for your server to get you started. If you want to set up a custom domain you will need to have some comfort with the command line interface. 
```

2021-02-21 06:58 UTC, britttttk commented on docs/LunaNodeWebDeployment.md
> +Their web-wizard is one of the easiest ways to **deploy BTCPay Servers from a very user-friendly interface**. This method is highly recommended if you don't have a lot of technical knowledge. However
Important to mention this, so that we don't intimidate non-technical users.

2021-02-21 18:15 UTC, zevaverbach reviewed
makes good sense to me!

2021-02-21 21:54 UTC, merged