R pi4 install
btcpayserver/btcpayserver-doc pull request #988
Opened 2021-11-27 10:45 UTC by lightninginabox

Update Raspberry Pi Instructions and added installation scripts for LND & CLightning

2021-11-27 12:34 UTC, Zaxounette requested changes
ACK grammar, format and such.

But you created .txt files.
@dennisreimann , are TXT files okay? I'd prefer having MD files all around, but if they're not a problem for deploying to the doc website...

2021-12-01 09:23 UTC, britttttk approved these changes

2021-12-01 13:14 UTC, Zaxounette approved these changes

2021-12-10 02:28 UTC, NicolasDorier commented
The scritps referenced do not exists

2021-12-10 02:29 UTC, NicolasDorier commented on docs/Deployment/RPi4.md
> +wget -O btcpayserver-install-lnd.sh https://raw.githubusercontent.com/btcpayserver/btcpayserver-doc/master/docs/Deployment/btcpayserver-lnd-rpi4-install.md
wat? you can execute a md file?

2021-12-10 02:29 UTC, NicolasDorier commented on docs/Deployment/RPi4.md
> +wget -O btcpayserver-install-clightning.sh https://raw.githubusercontent.com/btcpayserver/btcpayserver-doc/master/docs/Deployment/btcpayserver-clightning-rpi4-install.md
I don't execute md files!

2021-12-10 02:30 UTC, NicolasDorier commented
Even if they existed, I am wondering if we should provide at all the ready to run scripts.

2021-12-10 02:46 UTC, lightninginabox commented
The install scripts have .md extensions on GH, but the "wget" command renames them to .sh. They will exist on your repo if the PR gets merged. 

"**wget -O btcpayserver-install-clightning.sh** https://raw.githubusercontent.com/btcpayserver/btcpayserver-doc/master/docs/Deployment/btcpayserver-clightning-rpi4-install.md"

In my experience selling hardware nodes most people just want to get a "full node" up and running as quickly as possible and they work out the details later (Tor vs clear net, domain name, port forwarding etc.)  The benefit to having an install script it that saves the user a lot of copy & pasting from the instructions.

2021-12-10 15:00 UTC, pavlenex commented
> Even if they existed, I am wondering if we should provide at all the ready to run scripts.

This is just first step. First we create easy to run scripts, next step is to provide option for an image which would deploy Transmuter for people who need customisation. The reason Umbrel-like services are popular is because all of the pre-configured things. The simpler and easier the more people will opt in.

2021-12-16 14:26 UTC, merged